# Generated by Django 2.1.5 on 2019-05-27 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mngApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Song',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='message',
            new_name='title',
        ),
    ]
