# Generated by Django 2.1.5 on 2019-05-27 05:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mngApp', '0002_auto_20190527_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='bLv',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
