# Generated by Django 2.1.5 on 2019-05-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mngApp', '0004_auto_20190527_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='no',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
